### ISSUE TITLE
Does SnowAlert work on Windows? Getting "Error starting userland proxy..."

### ISSUE THREAD

**Issue by Ashok19r91d** [snowflakedb/SnowAlert#179]
executing docker of snowalert-webui with following command

`docker run -it -p 8000:8000 --env-file envfilename.envs snowsec/snowalert-webui` results in following error,

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint determined_chandrasekar (UNIQUE_IDENTIFIER): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8000:tcp:172.17.0.3:8000: input/output error.
```

**Comment by andrey-snowflake** [comment]
Googling around, this looks like an error that Docker has on Windows sometimes. Did you find a resolution, and are you sure this is SnowAlert specific?

**Comment by caonimademimi** [comment]
docker: Error response from daemon: mkdir /var/lib/docker/overlay2/7bbd46e82a6947e73d977ee2bcb6444e402de45d1137ccd52a1dae665c20deaa-init/merged/dev/shm: invalid argument.
I am reporting errors on the CentOS system.

**Comment by Ashok19r91d** [comment]
> Googling around, this looks like an error that Docker has on Windows sometimes. Did you find a resolution, and are you sure this is SnowAlert specific?
> @andrey-snowflake

Yes I'm using Windows as Host OS for Docker, and I'm not sure that this error is specific to SnowAlert. Is there any ways available to validate same
