### ISSUE TITLE
Feature: AWS VPC Flow Connector

### ISSUE THREAD

**Issue by edulop91** [snowflakedb/SnowAlert#247]
We would like to ingest VPC flow logs in a standardized way through a Snowalert Connector. 
Some info on their format: https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html#flow-log-records
Some code I wrote in some other project to ingest these into s3: https://github.com/chanzuckerberg/go-misc/blob/master/lambda/flow/s3.go

**Comment by greg-snowflake** [comment]
This is in progress already; it won't be in the 1.8.3 release (which is coming on 8/5), but will definitely be in 1.8.4 (which should release two weeks after). If you need it before it's officially released, I can point you to the branch when the code is complete.

**Comment by edulop91** [comment]
1.8.4 is great! Wanted to make sure we weren't duplicating efforts.

**Comment by edulop91** [comment]
https://github.com/snowflakedb/SnowAlert/pull/237 just for reference
