### ISSUE TITLE
Data Connector for Github Audit Logs

### ISSUE THREAD

**Issue by edulop91** [snowflakedb/SnowAlert#249]
I would like a connector to ingest github organization audit log events. These are provided to us through a webhook.

I currently have a simple webserver running that: reads/validates these webhooks -> firehose -> s3 -> snowflake.

**Comment by omer-snowflake** [comment]
We currently have a similar flow internally but use a SaaS ETL for the webhook. We want to move away from that ETL. Would you be willing to PR your webserver code to the scripts part of the SnowAlert project and we'll create a data connector to collect its output from S3?

**Comment by edulop91** [comment]
sounds good!

**Comment by andrey-snowflake** [comment]
Go code should be good. We might be able to get webhooks in the main product, so if there isn't a pressing reason to migrate now, converging then may make sense.
