### ISSUE TITLE
Data Connector for osquery

### ISSUE THREAD

**Issue by edulop91** [snowflakedb/SnowAlert#250]
i'm currently slurping osquery logs to snowflake:
endpoint -> kolide/fleet -> firehose -> s3 -> snowflake.

Wonder if it is worth standardizing how we ingest these logs in a connector. Another interesting aspect of osquery data is that we'll have snapshot data + event/stream data.

**Comment by omer-snowflake** [comment]
Good idea, we collect osquery from s3 internally so we'll prioritize building that into a connector next sprint. To help track this and other data connectors, I just created a project board. Check it out!
