### ISSUE TITLE
AWS Inventory connector uses AWS Access keys

### ISSUE THREAD

**Issue by edulop91** [snowflakedb/SnowAlert#275]
Wondering if there was a reason the AWS inventory connector is using AWS Access Keys instead of using dynamic credentials from a ec2/ecs/eks etc role.

**Comment by andrey-snowflake** [comment]
That's how someone contributed it, but we're open to ideas / discussion on how to best allow a variety of authentication mechanisms within all data connectors, so that they can create connections that use either roles or credentials.

**Comment by andrey-snowflake** [comment]
@greg-snowflake mentioned working on this soon. please link when you do!

**Comment by edulop91** [comment]
fixed in v1.8.6!
