### ISSUE TITLE
Changing OAuth role requires changing user's default role

### ISSUE THREAD

**Issue by edulop91** [snowflakedb/SnowAlert#302]
As far as I can tell, the oauth integration will only let you use the user's default role. I was wondering if it made sense to allow users to switch roles.

[update] As of v1.9.2 the WebUI admin can set `OAUTH_CONNECTION_ROLE` for the OAuth connections to use instead of the OAuth'ing users' default roles. The next iteration on this can provide an optional field in the `/login` form that lets the user enter any role they want.

**Comment by greg-snowflake** [comment]
Yep, this is a known issue; at some point we need to add a function to the UI which lets you switch roles in the session.

**Comment by andrey-snowflake** [comment]
We didn't have any other requests to allow users to pick a role (not against it, just not sure if it's needed), but we did get a PR that's going to be released in v1.9.2 that —

> Allows WebUI operator to set an envar role to use instead of the OAuth'd user's default role

Let me know if this helps the use-case that motivated this ticket, or if we should keep it open until we implement the fully customizable role.

**Comment by andrey-snowflake** [comment]
Going to close this for now, as the original issue is now resolved.

Let's make a separate one if there's a requirement to customize the role by-user (e.g. for read-only auditors and read-write engineers to use the same WebUI)?
