### ISSUE TITLE
NETWORK_PROTOCOL_MAPPING table empty

### ISSUE THREAD

**Issue by edulop91** [snowflakedb/SnowAlert#312]
Just created the VPC connector, data is being ingested well but the NETWORK_PROTOCOL_MAPPING table is empty. Starting to look into why this might be the case.

**Comment by andrey-snowflake** [comment]
Did you or @greg-snowflake get this tracked down? Is it something we can fix on our end?

**Comment by edulop91** [comment]
Yeah, fixed!
