### ISSUE TITLE
Document permissions required for Azure VM and Subscriptions Connectors

### ISSUE THREAD

**Issue by randypitcherii** [snowflakedb/SnowAlert#339]
For the Azure Subscriptions and Azure VM connectors, is there any documentation of any kind anywhere describing which permissions are expected in the Azure AD Application?

**Comment by andrey-snowflake** [comment]
Thanks for pointing out this gap in the docs -- it's Reader permissions in all of the subscriptions. Let me know if this makes sense or if I should expound.

**Comment by randypitcherii** [comment]
Andrey, thanks for the info. That helps a ton.

Do you know of Azure documentation or a blog post that sets up a similar connector that I can use as a pseudo-doc for these connections?

**Comment by andrey-snowflake** [comment]
Only the various permissions docs come to mind. What exactly would you like documented? Happy to fix UX bugs or add it to our connectors docs if anything is unclear.

**Comment by andrey-snowflake** [comment]
Hi @randypitcherii & Happy 2020. Let me know if I should keep this open or fix anything. Quick heads up re: these two connectors -- we're merging them and adding a lot more to launch a general "Azure Collect" connector which will handle Subscriptions, VMs, and quite a few other things. Let me know what kinds of documentation you'd like to see there or if you'd like help hooking it up to your accounts.

**Comment by andrey-snowflake** [comment]
Hi @randypitcherii -- I'm adding documentation about Reader role grants and Graph API permissions in the docs [here](https://github.com/snowflakedb/SnowAlert/blob/v1.9.2/docs/connectors/azure_collect/azure_collect.md). Please don't hesitate to re-open this issue if you'd like further details or instructions re: the other types in the new connector.
