### ISSUE TITLE
How to Ingest and Run All with the snowalert runner container?

### ISSUE THREAD

**Issue by randypitcherii** [snowflakedb/SnowAlert#340]
Is the current best practice for production Snowalert usage to run the runner container with `./run ingest` and `./run all` commands in production?

Is there a way to perform both tasks sequentially with a single docker command?

**Comment by andrey-snowflake** [comment]
Unless there's something in the `./src/ingestion` dir that catches your eye, we don't recommend running them at all. Even then, you might want to wait — by the end of the year we'll have moved all the functionality of `./run ingest` over to `./run connectors`, which is included in `./run all`.

**Comment by randypitcherii** [comment]
Is any of this documented? How do users figure this out?

**Comment by andrey-snowflake** [comment]
`./run all` is documented as the default setup, and `./run ingest` is not, as it was the initial version of our ingestion infra developed before we made anything other than the code public.

Usually users notice the Connectors section in the WebUI and ask us about it. Some of the more enterprising ones go ahead and read `run.py` to figure out what the runner options are ;-)
