### ISSUE TITLE
Connector roadmap | AWS IAM connector 

### ISSUE THREAD

**Issue by randypitcherii** [snowflakedb/SnowAlert#341]
Is there an AWS IAM connector for ingesting IAM users / groups from AWS? Is this part of the AWS Config connector or is it something else?

**Comment by andrey-snowflake** [comment]
We'll be adding base IAM data (`aws iam list-users`) to our v1.8.7 release with PR #332, due out next week, by adding the "IAM" type to our AWS Inventory Connector.

There's a bit more details that will be added in later versions, as well, e.g. mfa devices and access keys.

**Comment by omer-snowflake** [comment]
@randypitcherii this is now available as part of v1.9.0 under the AWS Collection data connector. Also check out the associated CIS AWS SQL pack. Hope it's useful, send us your feedback!
