### ISSUE TITLE
Data Connector for Salesforce Event Monitoring

### ISSUE THREAD

**Issue by hh-jamesweakley** [snowflakedb/SnowAlert#360]
See training material here: https://trailhead.salesforce.com/en/content/learn/modules/event_monitoring

These are the events that come with the Shield add-on, that act as an audit trail of user activity. The use case would be monitoring for suspicious CRM activity (e.g. viewing a suspiciously large number of different customer records)

User Login History (https://help.salesforce.com/articleView?id=users_login_history.htm&type=5) is another possible data source but is not as rich.

Note that someone from my company is likely to implement request this in the coming months, but registering interest in the meantime.

**Comment by omer-snowflake** [comment]
Thanks James, we have Shield too but haven't integrated it yet so this would be great to have. Is the person at your company going to implement to integration as a data connector to Snowflake?

**Comment by hh-jamesweakley** [comment]
Sorry @omer-snowflake, missed this comment at the time. Yes, we're planning to build a SnowAlert data connector for Salesforce Event Monitoring.

**Comment by andrey-snowflake** [comment]
Thanks again for the contribution, @hh-jamesweakley! Feel free to resolve when you have a working deployment with released code or we can when we do.

**Comment by andrey-snowflake** [comment]
Could you add a doc in `./docs/connectors` or write up here some instructions w.r.t. recommended usage for the connector? Should we be creating a service user to use this, and then the service user creates an API key? 

![image](https://user-images.githubusercontent.com/42752788/71841484-59411b00-3074-11ea-8a82-b475fb5fb6c4.png)

**Comment by andrey-snowflake** [comment]
Looking good, thanks again!
