### ISSUE TITLE
Database of WebUI OAuth user

### ISSUE THREAD

**Issue by hh-jamesweakley** [snowflakedb/SnowAlert#367]
I'm attempting to configure the Okta Data Connector using the Web UI, and I am using OAuth for the connection to Snowflake.

When I hit Create, I get the following error:
`snowflake.connector.errors.ProgrammingError: 090105 (22000): Cannot perform CREATE TABLE. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.`

Looking in the Snowflake history view, the query being ran is:
`CREATE TABLE data.okta_default_connection(raw VARIANT, event_time TIMESTAMP_LTZ)`

At a glance I think this is the part where database is cleared for oauth accounts:
https://github.com/snowflakedb/SnowAlert/blob/master/src/runners/helpers/db.py#L95

**Comment by hh-jamesweakley** [comment]
The intent of this commit:
https://github.com/snowflakedb/SnowAlert/commit/228a4a8106f1269efa64b822954b1b81c2633c63
appears too restrictive for us, I'm going to open a PR to propose an alternative

**Comment by andrey-snowflake** [comment]
Thanks for offering to offer a PR. The solution we intend here is to use a
default namespace on the SnowAlert user, e.g. —

ALTER USER afedorov SET DEFAULT_NAMESPACE='snowalert.rules';

It’s a stop-gap until we have bandwidth to add a proper selection from
SnowAlert databases in the UI (there may be several in an account), but
happy to take PR’s that make this easier, as well.

Happy to add this to the documentation, in our next release, as well.

**Comment by hh-jamesweakley** [comment]
Thanks @andrey-snowflake . I've subsequently discovered that the same applies to warehouse and role selection.

The PR I've opened hopefully clarifies my thinking. Happy to take feedback and adjust if necessary.

**Comment by andrey-snowflake** [comment]
Looks good to me, thanks. Merged into v1.9.2, will test and release early next week.
