### ISSUE TITLE
Docker tag for most recent development build

### ISSUE THREAD

**Issue by hh-jamesweakley** [snowflakedb/SnowAlert#375]
I see that in addition to "latest", upcoming releases typically have their [own tag](https://hub.docker.com/r/snowsec/snowalert/tags), which is great for keeping production up to date and testing particular release candidates.

Given the fast cadence of the product and the difficulty of testing outside of a prod-like environment, it would be handy to have a fixed-name tag that referenced the most recent build on a "version" branch (x.y.z). For example, right now it would point to the image built from the most recent commit on "v1.9.2", and it could just be called something like "dev".

We would then set our test environment deployments to use this tag, and it would mean:
1) We rely less on docker builds locally for other people's pre-release changes
2) We could keep data collectors running and potentially pick up on any issues on the leadup to a release

**Comment by hh-jamesweakley** [comment]
Actually I just noticed "1-rc" which was updated recently, what's that for?

**Comment by andrey-snowflake** [comment]
That's really close to what you're looking for, until a version 2 comes out (not currently on the roadmap). Happy to add a "dev" tag as well, if that would be preferred.

**Comment by hh-jamesweakley** [comment]
Great, thanks Andrey. Just for my benefit, what branch(es) is "1-rc" built from? and does it automatically reflect what's in the git repo?

**Comment by andrey-snowflake** [comment]
Anything pushed to branch `vA.B.C` is built to `A-rc`, `A.B-rc`, and `A.B.C-rc`. I didn't think to add one level higher when I was configuring it, but definitely makes sense to now that you mention it :-)

**Comment by hh-jamesweakley** [comment]
1-rc sounds like it'll do what I need, assuming major versions won't be too frequent.
