### ISSUE TITLE
Possible bug in Azure Active Directory Logs SnowAlert WebUI connector

### ISSUE THREAD

**Issue by plakhanpal** [snowflakedb/SnowAlert#376]
Hello,

I pulled the latest images of snowsec/snowalert and snowsec/snowalert-gui from dockerhub and tried to connect to Azure Active Directory Logs through the web portal. However, the following error is thrown: 

Unable to update graph with root task SNOWALERT.DATA.AZURE_LOG_AZUREADT3DEMO_AUDITLOGS_AUDIT_REFRESH_TASK since that root task is not suspended.

I see that the task calls procedure "AZURE_LOG_AZUREADT3DEMO_AUDITLOGS_AUDIT_PROCEDURE" which has a DDL statement, while the task itself is in started state. Not sure if the issue is related to "Per the Snowflake Tasks documentation for the AFTER parameter, you'll likely need to suspend the root task before you can run these, or use an equivalent non-DDL statement. Executing DDL commands on any task in a tree of tasks requires that the root task is suspended. If the root task is currently resumed, then the command returns a user error." Kindly look into it.

For your quick reference, I have posted the DDL of the procedure:

CREATE OR REPLACE PROCEDURE "AZURE_LOG_AZUREADT3DEMO_AUDITLOGS_AUDIT_PROCEDURE"()
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '

var sql_command = "ALTER EXTERNAL TABLE data.azure_log_AzureADT3Demo_AuditLogs_audit_external REFRESH";
try {
    snowflake.execute ({sqlText: sql_command});
    return "Succeeded.";
} catch (err)  {
    return "Failed: " + err;
}

';

**Comment by andrey-snowflake** [comment]
Did not test this well enough before release -- there's a bug in the fix that will be fixed in v1.9.4

**Comment by sfc-gh-afedorov** [comment]
This is fixed in v1.9.4, to be released shortly.
