### ISSUE TITLE
Possible bug: Jira integration issue type needed

### ISSUE THREAD

**Issue by plakhanpal** [snowflakedb/SnowAlert#377]
Hello,

In the snowsec/snowalert docker image hosted on dockerhub, specifying Jira integration as Y works on the install. However, when the snowalert docker container is run, no issues are created in Jira because the Jira REST API returns "Issue type not found" and hence, all the events in snowflake tables have null Jira Task IDs. I believe an Issue Type  needs to be added in the REST API call to JIRA. Please check.

**Comment by andrey-snowflake** [comment]
Thanks, @plakhanpal, and for the other report — I can customize the issue type, which is currently set to a constant —

~~~
    issue_params = {
        'project': project,
        'issuetype': {'name': 'Story'},
        'summary': alert['TITLE'],
        'description': body,
    }
~~~

Please let me know if you have a preference for how this is best solved, or I can figure out whatever makes the most sense to me.

**Comment by plakhanpal** [comment]
Hi Andrey,

I will go with whatever you recommend. My 2 cents:

1. Project - According to Jira developer url, it might be needed to pass “key” within “project” object. https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/#creating-an-issue-examples

2. Issue type - Either a Story or a Task could work. However, it would be great if a Story is created that represents issue category (for example: by connector type such  as Azure AD logs), and within a Story, a Task is added connected to that Story. This way, all tasks would stay within that single story and might be easier for categorization.

Great work on the snowalert framework by the way !

Regards,
Puneet Lakhanpal

**Comment by andrey-snowflake** [comment]
Hi Puneet — I'm not sure why Jira docs break out project into an object, but all our code uses the two or three-letter ID and it seems to work well. Happy to take a PR to make it match their docs, but I've updated the issue type to be customizable so that you can set the environment variable `JIRA_ISSUE_TYPE` to "Story" or "Task" as works best for the handler. Let me know if that's enough or if you'd like anything else.

**Comment by sfc-gh-afedorov** [comment]
I think this was added in the release and a separate ticket should be opened if that's not enough or if there's a bug in the UX or implementation.
