### ISSUE TITLE
Where Is This File? `packs/snowflake_query_pack.sql`

### ISSUE THREAD

**Issue by GalGreenfield** [snowflakedb/SnowAlert#380]
Hi,

Firstly, I want to mention that I'm new to Docker.
Secondly, I'm running Docker on Docker Desktop on Windows (and have the Docker CLI that came with it).

As for the problem:
[The docs](https://snowalert.readthedocs.io/en/latest/pages/manage.html) mention an alerts configuration file `packs/snowflake_query_pack.sql`.

Could you please tell me where is that file and how I can access it to view its contents?
I pulled the `snowalert` Docker image already.

Gal Grünfeld,
Developer @ Madtrix

**Comment by andrey-snowflake** [comment]
It's referring to [the repo](https://github.com/snowflakedb/SnowAlert/tree/master/packs) — can update docs to clarify.

**Comment by GalGreenfield** [comment]
Oh, okay, I understand now. Thanks for the clarification. :)
I think it'd be good to clarify the docs with this.

**Comment by andrey-snowflake** [comment]
Agreed -- let's keep it open so I remember to update docs before release.

**Comment by GalGreenfield** [comment]
Alright, then I won't close it again.
