### ISSUE TITLE
Can't Query + Can't Find SnowAlert's Database on Snowflake

### ISSUE THREAD

**Issue by GalGreenfield** [snowflakedb/SnowAlert#381]
Weird behavior in Snowflake:

I ran SnowAlert's install script, and it created the SnowAlert DB on Snowflake - as it should have, so all great so far.
(I also, unrelated or not, ran the `run` script - works fine, as well - does what it's supposed to do).

I can also see the `SNOWALERT` database exists in Snowflake's Web UI in Databases tab, see its content and so forth, but can't find it in the database objects explorer and I also can't also query it.

When I query it (in Worksheets - just a simple `USE DATABASE SNOWALERT`), I get the following error: 
> SQL compilation error: Object does not exist, or operation cannot be performed.

It doesn't make sense to me, since I'm logged with the same role as the owner of the SnowAlert database (`ACCOUNTADMIN`), and can *see* that it exists as oppose to the error, and I can't think of a reason for the operation to not be able to be performed.

How can I solve this issue? I'm trying to create my own rules to figure out how to use SnowAlert.

Could it be perhaps some sort of indexing/updating problem in Snowflake's objects collection, maybe because a script (SnowAlert's `install`) created this database?

**Comment by GalGreenfield** [comment]
Solution found: I was using `SYSADMIN` as the role on session-level in Workesheets while my account was using `ACCOUNTADMIN` - a bit confusing, I wasn't even aware of the session-level role.

**Comment by andrey-snowflake** [comment]
Yeah, that's a known UX problem folks run into — there's a solution in the works, sorry it got you :-)
