### ISSUE TITLE
Status of Version 1.93?

### ISSUE THREAD

**Issue by GalGreenfield** [snowflakedb/SnowAlert#387]
Hi, I got notifications about pull requests from @andrey-snowflake about v1.93 changes, and saw on Docker Hub that you've updated the `:latest` container just 2-3 hours ago from the time of me posting this question, and also that you have some images with "1.93" in their names - what are those?

I just want to understand if the update is live (not seeing it in `releases` here on GitHub or not yet, and if not, in how long you expect to deliver it - it might solve some issues we have with Jira.

**Comment by andrey-snowflake** [comment]
That sounds like it may have been a typo somewhere, but could you link to where you're seeing this?

We're working on v1.9.3 to be released shortly, but [latest](https://hub.docker.com/layers/snowsec/snowalert/latest/images/sha256-8cff01e16e3513fe353ae45f5dcdb2e14844796fc1a18ef29ae3fc37ea4a4901?context=explore) should still be from 15 days ago until the release.

**Comment by GalGreenfield** [comment]
Okay, thanks for the clarification.

Here's where I saw this: https://hub.docker.com/r/snowsec/snowalert/tags
(Update, now seeing only one such image)

**Comment by andrey-snowflake** [comment]
Yes, `v1.9.3-rc` is definitely going to be built repeatedly as I develop it (and as Docker Hub catches up to the pushes to the release branch). Feel free to use that to get the features listed in the [pre-release notes](https://github.com/snowflakedb/SnowAlert/pull/383).

Not sure what to do about the weirdness on Docker Hub last night, but not seeing anything that could have caused it from my end. Moving to AWS for build infra has been a long-standing piece of tech debt for us, so will keep this in mind next time we re-prioritize.

**Comment by GalGreenfield** [comment]
Alright, thanks for the clarification - I wasn't sure what `v.1.9.3-rc` was.
Do you think that with the update you made that it'll solve the issue I have with Jira?

**Comment by GalGreenfield** [comment]
Alright, thanks for the clarification - I wasn't sure what `v.1.9.3-rc` was.
Do you think that with the update you made that it'll solve the issue I have with Jira?

**Comment by andrey-snowflake** [comment]
Yup, `rc` stands for "release candidate". I looked into it a bit more just now and the Jira error looks like a bug in the Jira handler — I was going to leave it for v1.9.4, but it having gotten latter in the week, I think we'll be OK fixing it now and releasing early next week. Let me circle back in #382 comments to understand the error better.
