### ISSUE TITLE
Epic link needed on JIRA issue Creation

### ISSUE THREAD

**Issue by ykwek** [snowflakedb/SnowAlert#394]
Is there an way to add other required fields that may be needed on JIRA ticket creations ? Jira creation in my company would required Epic field  selected.

**Comment by sfc-gh-afedorov** [comment]
Sorry it took me a little while to realize that Epics were just another custom field in Jira, and we already have this functionality -- e.g. in our test project, we can set the `SA_JIRA_CUSTOM_FIELDS` environment variable to "`10012=key:SAT-1193`" to set the Epic to that ticket. Let me know if you have trouble with this and can help debug issues.

**Comment by sfc-gh-afedorov** [comment]
apologies -- just tested this, found an issue with setting the epic field and fixed it in [e7257f6](https://github.com/snowflakedb/SnowAlert/commit/e7257f6e55ce07ec09137d431b62497dc1ff740a)
