### ISSUE TITLE
Misspelled datatype in AWS Inventory and Configuration Data Connection

### ISSUE THREAD

**Issue by Chaitali-Sonparote** [snowflakedb/SnowAlert#399]
Hello,

I have configured the AWS Inventory and Configuration Data Connection and got the error as below on the WebUI - "snowflake.connector.errors.ProgrammingError: 002040 (42601): SQL compilation error: Unsupported data type 'VARAINT'."

**Comment by sfc-gh-afedorov** [comment]
Thanks, fixed in d8394f2.
