### ISSUE TITLE
s3:get_public_access_block

### ISSUE THREAD

**Issue by edulop91** [snowflakedb/SnowAlert#453]
Hello! I was wondering if there was any interest in adding the [s3:get_public_access_block](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.get_public_access_block) to the aws collect connector.

If so, I'd be happy to contribute the code :smile:

**Comment by sfc-gh-afedorov** [comment]
Sounds useful, would appreciate, thank you!

**Comment by sfc-gh-afedorov** [comment]
Added it to the v1.10.0 release via PR #459

Could you please double check it's working as intended, @edulop91 ?

**Comment by edulop91** [comment]
Verified, thank you @sfc-gh-afedorov !
