### ISSUE TITLE
Mails to multiple users

### ISSUE THREAD

**Issue by manideepa** [snowflakedb/SnowAlert#533]
Hi,
I see there is a SMTP handler. I want to configure it to send to mails to users if there is a login failure. That is I want to send a mail from the mail column of respective user in snowflake.account_usage.users view. Is this possible? If so how can I configure it?

**Comment by sfc-gh-afedorov** [comment]
Yes, the alert query can map the column to a value in the email handler column's objects, including the "to" field.

**Comment by manideepa** [comment]
Will something something like this in the handler column"
OBJECT_CONSTRUCT(
'type','smtp',
'sender_email','alerts@yourdomain.com',
'recipient_email','select email from snowflake.account_usage.users u inner join snowflake.account_usage.login l on u.name=l.user_name and is_success='NO'',
'subject','test',
'text','This is a test mail')
AS handlers

**Comment by sfc-gh-afedorov** [comment]
Something like it, yes, but for the sub-query you want it in parentheses and some way of making sure the result only has a single value (e.g. `LIMIT 1`) at the end of the query.
