### ISSUE TITLE
Snowalert install with SSO error

### ISSUE THREAD

**Issue by vamsikt** [snowflakedb/SnowAlert#640]
Hi,

We are exploring the Snowalert and trying to run using the Getting started [guide](https://snowalert.readthedocs.io/en/latest/pages/start.html). We encounter issue where the SSO authentication hangs forever..
Steps to reproduce :

1. docker run -it snowsec/snowalert ./install
2. enter the snowflake account
3. enter the user name (with account admin access)
4. enter password: left blank for SSO
5. Click below URL
After clicking the URL it was redirected to snowflake login and after login, it was tried to redirect to localhost:1901 as there is no service running.

how can we use SSO during install?

**Comment by nfillot** [comment]
Hey @vamsikt 

Try to publish the port 1901 for SSO auth

`docker run -it -p 1901:1901 snowsec/snowalert ./install`

The result should be 
` Your identity was confirmed and propagated to Snowflake PythonConnector. You can close this window now and go back where you started from. `
